import { afterEach, describe, expect, it } from "vitest";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {
  generateQuarantineIndex,
  parkQuarantinedTest,
  QUARANTINE_DIR,
  QUARANTINE_INDEX_FILE,
  QUARANTINE_ORIGINS_FILE,
  QuarantineError,
} from "./quarantine.js";

describe("quarantine routing", () => {
  const tmpDirs: string[] = [];

  function makeRepo(): string {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "march-quarantine-test-"));
    tmpDirs.push(dir);
    return dir;
  }

  afterEach(() => {
    for (const dir of tmpDirs) {
      try {
        fs.rmSync(dir, { recursive: true, force: true });
      } catch {
        // best-effort cleanup
      }
    }
    tmpDirs.length = 0;
  });

  it("parks a test under tests/quarantine while preserving the file body", () => {
    const repoRoot = makeRepo();
    const origin = "src/example/foo.test.ts";
    const originAbs = path.join(repoRoot, origin);
    const body = [
      "/* @scope unit @determinism deterministic @channel ci */",
      "import { describe, expect, it } from \"vitest\";",
      "",
      "describe(\"foo\", () => {",
      "  it(\"keeps assertions\", () => {",
      "    expect(1 + 1).toBe(2);",
      "  });",
      "});",
      "",
    ].join("\n");
    fs.mkdirSync(path.dirname(originAbs), { recursive: true });
    fs.writeFileSync(originAbs, body);

    const result = parkQuarantinedTest(origin, { repoRoot });

    expect(result).toEqual({
      originPath: origin,
      quarantinedPath: `${QUARANTINE_DIR}/${origin}`,
    });
    expect(fs.existsSync(originAbs)).toBe(false);
    expect(fs.readFileSync(path.join(repoRoot, result.quarantinedPath), "utf-8"))
      .toBe(body);
  });

  it("records the origin path when parking", () => {
    const repoRoot = makeRepo();
    const origin = "src/example/bar.test.ts";
    fs.mkdirSync(path.join(repoRoot, "src/example"), { recursive: true });
    fs.writeFileSync(path.join(repoRoot, origin), "import \"vitest\";\n");

    const result = parkQuarantinedTest(origin, { repoRoot });

    const manifest = JSON.parse(
      fs.readFileSync(path.join(repoRoot, QUARANTINE_ORIGINS_FILE), "utf-8"),
    ) as Record<string, string>;
    expect(manifest).toEqual({ [result.quarantinedPath]: origin });
    expect(fs.readFileSync(path.join(repoRoot, QUARANTINE_INDEX_FILE), "utf-8"))
      .toContain(`| \`${result.quarantinedPath}\` | \`${origin}\` |`);
  });

  it("generates a populated index from quarantined tests and recorded origins", () => {
    const repoRoot = makeRepo();
    const first = `${QUARANTINE_DIR}/src/alpha/a.test.ts`;
    const second = `${QUARANTINE_DIR}/src/beta/b.test.ts`;
    fs.mkdirSync(path.join(repoRoot, path.dirname(first)), { recursive: true });
    fs.mkdirSync(path.join(repoRoot, path.dirname(second)), { recursive: true });
    fs.writeFileSync(path.join(repoRoot, first), "import \"vitest\";\n");
    fs.writeFileSync(path.join(repoRoot, second), "import \"vitest\";\n");
    fs.writeFileSync(
      path.join(repoRoot, QUARANTINE_ORIGINS_FILE),
      JSON.stringify({
        [second]: "src/beta/b.test.ts",
        [first]: "src/alpha/a.test.ts",
      }),
    );

    const result = generateQuarantineIndex({ repoRoot });

    expect(result.entries).toEqual([
      { quarantinedPath: first, originPath: "src/alpha/a.test.ts" },
      { quarantinedPath: second, originPath: "src/beta/b.test.ts" },
    ]);
    expect(fs.readFileSync(path.join(repoRoot, QUARANTINE_INDEX_FILE), "utf-8"))
      .toBe([
        "# Quarantined Tests",
        "",
        "_Generated by `march quarantine index`. Do not edit by hand._",
        "",
        "| Quarantined Path | Origin Path |",
        "|------------------|-------------|",
        `| \`${first}\` | \`src/alpha/a.test.ts\` |`,
        `| \`${second}\` | \`src/beta/b.test.ts\` |`,
        "",
      ].join("\n"));
  });

  it("regenerates the index without stale rows after quarantine contents change", () => {
    const repoRoot = makeRepo();
    const stale = `${QUARANTINE_DIR}/src/stale.test.ts`;
    const current = `${QUARANTINE_DIR}/src/current.test.ts`;
    fs.mkdirSync(path.join(repoRoot, QUARANTINE_DIR, "src"), { recursive: true });
    fs.writeFileSync(path.join(repoRoot, stale), "import \"vitest\";\n");
    fs.writeFileSync(
      path.join(repoRoot, QUARANTINE_ORIGINS_FILE),
      JSON.stringify({
        [stale]: "src/stale.test.ts",
        [current]: "src/current.test.ts",
      }),
    );
    generateQuarantineIndex({ repoRoot });

    fs.rmSync(path.join(repoRoot, stale));
    fs.writeFileSync(path.join(repoRoot, current), "import \"vitest\";\n");
    generateQuarantineIndex({ repoRoot });

    const index = fs.readFileSync(path.join(repoRoot, QUARANTINE_INDEX_FILE), "utf-8");
    expect(index).not.toContain(stale);
    expect(index).toContain(`| \`${current}\` | \`src/current.test.ts\` |`);
  });

  it("generates an empty index when no tests are quarantined", () => {
    const repoRoot = makeRepo();

    const result = generateQuarantineIndex({ repoRoot });

    expect(result.entries).toEqual([]);
    expect(fs.readFileSync(path.join(repoRoot, QUARANTINE_INDEX_FILE), "utf-8"))
      .toBe([
        "# Quarantined Tests",
        "",
        "_Generated by `march quarantine index`. Do not edit by hand._",
        "",
        "No quarantined tests.",
        "",
      ].join("\n"));
  });

  it("raises a QuarantineError when the index file cannot be written", () => {
    const repoRoot = makeRepo();
    // Occupy the INDEX.md path with a directory so writeFileSync fails (EISDIR).
    fs.mkdirSync(path.join(repoRoot, QUARANTINE_INDEX_FILE), { recursive: true });

    expect(() => generateQuarantineIndex({ repoRoot })).toThrow(QuarantineError);
  });

  it("fails deterministically for invalid and already-quarantined inputs", () => {
    const repoRoot = makeRepo();
    const quarantined = `${QUARANTINE_DIR}/src/example/baz.test.ts`;
    fs.mkdirSync(path.join(repoRoot, path.dirname(quarantined)), { recursive: true });
    fs.writeFileSync(path.join(repoRoot, quarantined), "import \"vitest\";\n");

    expect(() => parkQuarantinedTest("src/example/not-a-test.ts", { repoRoot }))
      .toThrow(QuarantineError);
    expect(() => parkQuarantinedTest(quarantined, { repoRoot }))
      .toThrow(QuarantineError);
  });

  it("rolls the move back when the origin manifest cannot be written", () => {
    const repoRoot = makeRepo();
    const origin = "src/example/qux.test.ts";
    const body = "import \"vitest\";\n";
    fs.mkdirSync(path.join(repoRoot, "src/example"), { recursive: true });
    fs.writeFileSync(path.join(repoRoot, origin), body);
    // Force the manifest write to fail: occupy its path with a directory so
    // writeFileSync throws EISDIR after the file has already been moved.
    fs.mkdirSync(path.join(repoRoot, QUARANTINE_ORIGINS_FILE), { recursive: true });

    expect(() => parkQuarantinedTest(origin, { repoRoot })).toThrow(QuarantineError);
    // The move is rolled back: the test is back at its origin, not stranded
    // under quarantine with no recorded origin.
    expect(fs.readFileSync(path.join(repoRoot, origin), "utf-8")).toBe(body);
    expect(fs.existsSync(path.join(repoRoot, QUARANTINE_DIR, origin))).toBe(false);
  });

  it("still parks (without throwing) when the roster cannot be refreshed", () => {
    const repoRoot = makeRepo();
    const origin = "src/example/quux.test.ts";
    const body = "import \"vitest\";\n";
    fs.mkdirSync(path.join(repoRoot, "src/example"), { recursive: true });
    fs.writeFileSync(path.join(repoRoot, origin), body);
    // Force only the derived INDEX.md write to fail (directory at its path).
    // The durable quarantine (move + origin record) must still succeed.
    fs.mkdirSync(path.join(repoRoot, QUARANTINE_INDEX_FILE), { recursive: true });

    const result = parkQuarantinedTest(origin, { repoRoot });

    const quarantinedPath = `${QUARANTINE_DIR}/${origin}`;
    expect(result.quarantinedPath).toBe(quarantinedPath);
    expect(result.indexWarning).toContain(QUARANTINE_INDEX_FILE);
    // Durable quarantine intact: file moved and origin recorded.
    expect(fs.existsSync(path.join(repoRoot, origin))).toBe(false);
    expect(fs.readFileSync(path.join(repoRoot, quarantinedPath), "utf-8")).toBe(body);
    expect(
      JSON.parse(
        fs.readFileSync(path.join(repoRoot, QUARANTINE_ORIGINS_FILE), "utf-8"),
      ) as Record<string, string>,
    ).toEqual({ [quarantinedPath]: origin });
  });
});
