import fs from "node:fs";
import path from "node:path";

export const QUARANTINE_DIR = "tests/quarantine";
export const QUARANTINE_ORIGINS_FILE = `${QUARANTINE_DIR}/.origins.json`;
export const QUARANTINE_INDEX_FILE = `${QUARANTINE_DIR}/INDEX.md`;

export class QuarantineError extends Error {}

export interface ParkQuarantineResult {
  readonly originPath: string;
  readonly quarantinedPath: string;
}

export interface QuarantineIndexEntry {
  readonly quarantinedPath: string;
  readonly originPath: string;
}

export interface GenerateQuarantineIndexResult {
  readonly indexPath: string;
  readonly entries: readonly QuarantineIndexEntry[];
}

type OriginManifest = Record<string, string>;

function toRepoRelativePath(input: string): string {
  const trimmed = input.trim();
  if (trimmed.length === 0) {
    throw new QuarantineError("Provide a repo-relative *.test.ts path to park.");
  }
  if (path.isAbsolute(trimmed)) {
    throw new QuarantineError("Provide a repo-relative path, not an absolute path.");
  }

  const normalized = path.normalize(trimmed).replaceAll(path.sep, "/");
  if (normalized === "." || normalized.startsWith("../") || normalized === "..") {
    throw new QuarantineError("Path must stay inside the repository.");
  }
  return normalized;
}

function manifestPath(repoRoot: string): string {
  return path.join(repoRoot, QUARANTINE_ORIGINS_FILE);
}

function readManifest(repoRoot: string): OriginManifest {
  const file = manifestPath(repoRoot);
  if (!fs.existsSync(file)) {
    return {};
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(fs.readFileSync(file, "utf-8"));
  } catch (err) {
    throw new QuarantineError(
      `Could not read ${QUARANTINE_ORIGINS_FILE}: ${(err as Error).message}`,
    );
  }

  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new QuarantineError(`${QUARANTINE_ORIGINS_FILE} must contain a JSON object.`);
  }

  const manifest: OriginManifest = {};
  for (const [key, value] of Object.entries(parsed)) {
    if (typeof value !== "string") {
      throw new QuarantineError(`${QUARANTINE_ORIGINS_FILE} has a non-string origin.`);
    }
    manifest[key] = value;
  }
  return manifest;
}

function writeManifest(repoRoot: string, manifest: OriginManifest): void {
  fs.mkdirSync(path.join(repoRoot, QUARANTINE_DIR), { recursive: true });
  fs.writeFileSync(
    manifestPath(repoRoot),
    JSON.stringify(
      Object.fromEntries(Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b))),
      null,
      2,
    ) + "\n",
  );
}

function listQuarantinedTests(repoRoot: string): string[] {
  const root = path.join(repoRoot, QUARANTINE_DIR);
  if (!fs.existsSync(root)) {
    return [];
  }

  const files: string[] = [];
  const visit = (dir: string): void => {
    for (const item of fs.readdirSync(dir, { withFileTypes: true })) {
      const absolutePath = path.join(dir, item.name);
      if (item.isDirectory()) {
        visit(absolutePath);
        continue;
      }
      if (!item.isFile() || !item.name.endsWith(".test.ts")) {
        continue;
      }
      files.push(path.relative(repoRoot, absolutePath).replaceAll(path.sep, "/"));
    }
  };

  visit(root);
  return files.sort((a, b) => a.localeCompare(b));
}

function markdownCell(value: string): string {
  return value.replaceAll("|", "\\|");
}

function renderIndex(entries: readonly QuarantineIndexEntry[]): string {
  const lines = [
    "# Quarantined Tests",
    "",
    "_Generated by `march quarantine index`. Do not edit by hand._",
    "",
  ];

  if (entries.length === 0) {
    lines.push("No quarantined tests.", "");
    return lines.join("\n");
  }

  lines.push("| Quarantined Path | Origin Path |");
  lines.push("|------------------|-------------|");
  for (const entry of entries) {
    lines.push(
      `| \`${markdownCell(entry.quarantinedPath)}\` | \`${markdownCell(entry.originPath)}\` |`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

export function generateQuarantineIndex(options?: {
  readonly repoRoot?: string;
}): GenerateQuarantineIndexResult {
  const repoRoot = options?.repoRoot ?? process.cwd();
  const manifest = readManifest(repoRoot);
  const entries = listQuarantinedTests(repoRoot).map((quarantinedPath) => {
    const originPath = manifest[quarantinedPath];
    if (!originPath) {
      throw new QuarantineError(
        `${quarantinedPath} has no recorded origin in ${QUARANTINE_ORIGINS_FILE}.`,
      );
    }
    return { quarantinedPath, originPath };
  });

  fs.mkdirSync(path.join(repoRoot, QUARANTINE_DIR), { recursive: true });
  fs.writeFileSync(path.join(repoRoot, QUARANTINE_INDEX_FILE), renderIndex(entries));

  return { indexPath: QUARANTINE_INDEX_FILE, entries };
}

export function parkQuarantinedTest(inputPath: string, options?: {
  readonly repoRoot?: string;
}): ParkQuarantineResult {
  const repoRoot = options?.repoRoot ?? process.cwd();
  const originPath = toRepoRelativePath(inputPath);

  if (!originPath.endsWith(".test.ts")) {
    throw new QuarantineError("Only *.test.ts files can be parked in quarantine.");
  }
  if (originPath === QUARANTINE_DIR || originPath.startsWith(`${QUARANTINE_DIR}/`)) {
    throw new QuarantineError(`${originPath} is already under ${QUARANTINE_DIR}.`);
  }

  const sourcePath = path.join(repoRoot, originPath);
  if (!fs.existsSync(sourcePath) || !fs.statSync(sourcePath).isFile()) {
    throw new QuarantineError(`${originPath} does not exist or is not a file.`);
  }

  const quarantinedPath = `${QUARANTINE_DIR}/${originPath}`;
  const targetPath = path.join(repoRoot, quarantinedPath);
  if (fs.existsSync(targetPath)) {
    throw new QuarantineError(`${quarantinedPath} already exists.`);
  }

  const manifest = readManifest(repoRoot);
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.renameSync(sourcePath, targetPath);

  manifest[quarantinedPath] = originPath;
  try {
    writeManifest(repoRoot, manifest);
  } catch (err) {
    // Roll back the move so a manifest-write failure does not leave the repo
    // in a partially-parked state (file relocated, origin unrecorded).
    try {
      fs.renameSync(targetPath, sourcePath);
    } catch {
      // best-effort rollback
    }
    throw new QuarantineError(
      `Could not record the parked origin in ${QUARANTINE_ORIGINS_FILE}: ${(err as Error).message}`,
    );
  }

  generateQuarantineIndex({ repoRoot });

  return { originPath, quarantinedPath };
}
